server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8091
  servlet:
    context-path: /yibanke-api
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: admin
      password: abc123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.yibanke.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

sa-token:
  #token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  #关闭读取Cookie中Token
  isReadCookie: true


tencent:
  cloud:
    appId: 1309815830
    secretId: AKIDMXS6TZOwDCuLVOzKOBhwvd4D6i25rMaX
    secretKey: h8IAm7ByUjhOoxpQjlX2GDtIQHrACxQd
    region: ap-beijing
    bucket: emos-1309815830
  trtc:
    appId: 1400657697
    secretKey: aec511cc68381274a086098b29bc02ce0c6f546bfb66e05fa7f9e7752a3ab900
    expire: 86400

#微信支付
wx:
  app-id: wx4cb8e9621950da45
  app-secret: 9d80f4125c50e1cf8bc6031c9319b2df
  mch-id: 1526972031
  key: qv9Kihy5TOJxGySzFO8pd4wCMg3tn6YK
  cert-path: D:/DP__yibanke/apiclient_cert.p12

emos:
  code: "A64569E606CF30BB"
  tcode: "231310"
  recieveNotify: http://127.0.0.1:8091/yibanke-api/meeting/recieveNotify
#code 30天更新一次
#tcode 需要两个小时更新一次

workflow:
  url: http://127.0.0.1:9091/emos-workflow
# java -jar -Dfile.encoding=utf-8 emos-workflow.jar --spring.config.location=application.yml

#INSERT INTO `emos`.`tb_user` (`id`, `username`, `password`, `open_id`, `nickname`, `photo`, `name`, `sex`, `tel`, `email`, `hiredate`, `role`, `root`, `dept_id`, `status`, `create_time`) VALUES (71, 'admin', 'E15F671BE4D965A790689456ED3B4B90', 'oNlSI5C2Ih9Qw6kjPjl7TnKrAEws', '管理员', 'https://emos-1309815830.cos.ap-beijing.myqcloud.com/header/1.jpg', '娄梦', '女', '13312345678', 'loumeng@163.com', '2021-07-07', '[0, 1]', 1, 1, 1, '2021-11-16 12:11:33');


